name: RDP via Ngrok

on: [workflow_dispatch]

jobs:
  rdp:
    runs-on: windows-2022
    timeout-minutes: 360 # 6 hours max allowed by GitHub

    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath $Env:USERPROFILE\ngrok

    - name: Authenticate Ngrok
      run: |
        $Env:Path += ";$Env:USERPROFILE\ngrok"
        ngrok config add-authtoken $Env:NGROK_AUTH_TOKEN

    - name: Enable RDP
      run: |
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0

    - name: Set RDP Password
      run: |
        net user runneradmin "GitHub@12345"

    - name: Start Ngrok Tunnel
      run: |
        Start-Process -NoNewWindow -FilePath "$Env:USERPROFILE\ngrok\ngrok.exe" -ArgumentList "tcp 3389"

    - name: Show Connection Info
      run: |
        Start-Sleep -Seconds 20
        $tunnelInfo = Invoke-RestMethod -Uri http://127.0.0.1:4040/api/tunnels
        $publicUrl = $tunnelInfo.tunnels[0].public_url
        Write-Host "🔗 Connect to your RDP via:"
        Write-Host "👉 Host: $($publicUrl -replace 'tcp://', '')"
        Write-Host "🧑‍💻 User: runneradmin"
        Write-Host "🔐 Pass: GitHub@12345"

    - name: Keep Alive
      run: |
        Write-Host "🕒 Keeping runner alive for 6 hours..."
        Start-Sleep -Seconds 21600 # 6 hours
